language: android
jdk: oraclejdk8

# https://docs.travis-ci.com/user/languages/android/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
  - ANDROID_NDK_VERSION=r15c
  - ANDROID_NDK_HOME=/opt/android-ndk
  - ADB_INSTALL_TIMEOUT=20
  - CMAKE_VERSION=cmake-3.10.2
  - ANDROID_BUILD_TOOLS_VERSION=28.0.2
before_install:
  # Install SDK license so Android Gradle plugin can install deps.
- mkdir "$ANDROID_HOME/licenses" || true
- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager).
- sdkmanager tools
  # Install the system image.
- sdkmanager "system-images;android-21;default;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  # - echo no | avdmanager create avd --force -n test -k "system-images;android-21;default;armeabi-v7a"
  # - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
- rm -rf "$ANDROID_NDK_HOME"
- mkdir /opt/android-ndk-tmp
- cd /opt/android-ndk-tmp
- wget -q https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
  | cat
- unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip | cat
- mv ./android-ndk-${ANDROID_NDK_VERSION} ${ANDROID_NDK_HOME}
- cd ${ANDROID_NDK_HOME}
- rm -rf /opt/android-ndk-tmp
- cd ${TRAVIS_BUILD_DIR}
install:
- echo y | sdkmanager 'cmake;3.10.2.4988404' | grep -v "=$"
- echo y | sdkmanager 'lldb;3.0' | grep -v "=$"
before_script:
- export ANDROID_NDK_HOME=$ANDROID_NDK_HOME
#  - android-wait-for-emulator
#  - adb shell settings put global window_animation_scale 0 &
#  - adb shell settings put global transition_animation_scale 0 &
#  - adb shell settings put global animator_duration_scale 0 &
#  - adb shell input keyevent 82 &

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-15
  - android-25
  - android-21
  - android-28
    # Support library
  - extra-android-support
    # Latest artifacts in local repository
  - extra-google-m2repository
  - extra-android-m2repository
    # Specify at least one system image
    # - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL

    #allow licenses
  licenses:
  - android-sdk-preview-license-+
  - android-sdk-license-.+
  - google-gdk-license-.+
notifications:
  email: false
script:
- "./gradlew test"
- "./gradlew assemble_testNet3Debug"
- rm -rf .gradle/4.4
- "./gradlew assembleProdDebug"
- "./gradlew assembleProdRelease"
deploy:
  provider: releases
  api_key:
    secure: HnAH0AJL7/9ar2sTiQls2XarwhGETRSPpoNA+hGpI8xHp9bwH00lpSxQ2p69f4BTszUq4IY77fayYIgZIhhg3b/2NRuC61b94kTF3acXJNkMYkin9Vq/CmYqHWK0Z4AgjPCv9TMZzNvpzaEXLQtEWGBIxQYLXXz9PHjVOTIU+ye6OSkj9TcrZRsyib1iHevQfxBcT0haDkk//fQ1Fsfvvd0yV/k/b7xLJI/y3bB0eYk5vA/e2ufT/ZSTemrUV1cpR0f86xcFYo+AQS9C1v0jVyyWBzDQLbCDGlFjvbvPKQHA9bi6gw06nPFLXDqz6FWFAPvG3pTjRFublc3AAjOjdxLoCSBTUsWKvTkJg5z1goBKzBId0tfRnKF6RHY77DfRxHhUIUOmgpai4GHZx6bJKMqzytI6rq0fu974nyH806u1VZm6axe2nM21fD7cxpJ27ck9FzCDi/5ujGO19RPVdx33NxCyzaa1kvl/G7+RfbbpMS6liTe12kYEhWxMD2SanWWl+P8XNexK6VMwsg3RH+3XHlTl1iW8ID+++ULwVXTLiAhWsQrCJV3bjsmol24vN4n6E63wQe7mf61mXVbwB72BKCaSd3pQ635ytkefvt8Z2N+KklUOjDdXWytAz8DaBfRFVmefdMAv55liV25iVYA6+sAuYc7Q/QOun2ZnQbw=
  file: wallet/build/outputs/apk/wallet*release*.apk
  overwrite: true
  skip_cleanup: true
  on:
    branch: develop
    repo: dashevo/dash-wallet

after_success:
  - sh set_tags.sh